### ISSUE TITLE
runJest: Error: Cannot find module 'jest-cli/build/cli/args'

### ISSUE THREAD

**Issue by goulu** [ionic-team/stencil#2942]
**Stencil version:**
(with jest and jest-cli) 
```
+-- @ionic/core@5.6.10
| +-- @stencil/core@2.6.0  deduped
| `-- ionicons@5.5.2
|   `-- @stencil/core@2.6.0  deduped
+-- @stencil/core@2.6.0
+-- jest@27.0.5
| `-- jest-cli@27.0.5  deduped
`-- jest-cli@27.0.5
```

**I'm submitting a:**

[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
any call to stencil test ... builds, then causes
```
[ ERROR ]  runJest: Error: Cannot find module 'jest-cli/build/cli/args' Require stack: -
           C:\Users\guglie0p\AppData\Roaming\npm\node_modules\@stencil\core\testing\index.js -
           C:\Users\guglie0p\AppData\Roaming\npm\node_modules\@stencil\core\cli\index.cjs -
           C:\Users\guglie0p\AppData\Roaming\npm\node_modules\@stencil\core\bin\stencil
```
(on Windows...)

**Expected behavior:**
run the tests 
( worked with   @stencil/core": "^2.5.2",  "@types/jest": "^26.0.20" , will revert to these versions ...)

**Comment by splitinfinities** [comment]
Will be solved with #2980

**Comment by goulu** [comment]
just tested with
`+-- @ionic/core@5.6.13
| +-- @stencil/core@2.6.0
| `-- ionicons@5.5.3
|   `-- @stencil/core@2.6.0 deduped
+-- jest-cli@27.0.6
+-- jest@27.0.6
| `-- jest-cli@27.0.6 deduped`

and got 

`runJest: Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './build/cli/args' is not defined by
           "exports" in C:\path\package.json`

@splitinfinities how can I test #2980 please ? 
npm i -g git@github.com:ionic-team/stencil.git#STENCIL-17-upgrade-jest ?

**Comment by splitinfinities** [comment]
@goulu we're still working on it. We'll likely let folks know there when this is ready to test. There are broader implications we need to work our around this regarding the TS Typings.

**Comment by raphzandrade** [comment]
Also ran into this problem updating jest and jest-cli to 27.2.3. Any fixes?

**Comment by dkhir** [comment]
Also ran into this problem updating jest and jest-cli to 27.2.1 version.

**Comment by dcxn** [comment]
Still present for me as well with jest and jest-cli v27.4.5.

**Comment by rwaskiewicz** [comment]
https://github.com/ionic-team/stencil/pull/3189 includes support for Jest 27, and will be included in the next minor release of Stencil (v2.13.0)

**Comment by rrdlpl** [comment]
still fails on v27.4.7
any solution for this?

**Comment by markcellus** [comment]
Is it time to consider #3156 ? 😛

**Comment by rwaskiewicz** [comment]
Hey folks, this should be fixed in v2.13.0 of Stencil, which was just released with Jest 27 support. I'm going to close this issue for now, but if this comes up again, please feel free to file a new ticket!

**Comment by markcellus** [comment]
Hey @rwaskiewicz I appreciate you all wanting to close out issues but your use of the word "should" indicates that you all havent verified that the issue is actually fixed. Issues shouldnt be closed out unless they've been verified by your team. Waiting for someone to have the issue and file another ticket does a big disservice to the people who are watching this issue because they won't know about the new ticket.

**Comment by rwaskiewicz** [comment]
Hey @markcellus,

Thanks for the feedback! By no means meant to cause confusion or indicate that the Stencil team hadn't verified this bug was not fixed.  

To clarify, the cause of this bug has been root caused and the fix was implemented over the course of two PRs - https://github.com/ionic-team/stencil/pull/3189 & https://github.com/ionic-team/stencil/pull/3171.  The fix has been tested against Stencil projects both large and small by the team, and we are confident the [v2.13.0](https://github.com/ionic-team/stencil/releases/tag/v2.13.0) release fixes the issue described here.

I'll look towards using less ambiguous language in these comments in the future.

Thanks again!

**Comment by dcxn** [comment]
Can confirm this fixed the issue on my pipelines. Thank you
