### ISSUE TITLE
Build output does not always contain required components

### ISSUE THREAD

**Issue by cjorasch** [ionic-team/stencil#513]
**Stencil version:**
```
 @stencil/core@0.4.0
```

**I'm submitting a:**
- [x] bug report

**Current behavior:**
If I create a component using `document.createElement` then the component does not necessarily exist in the www build output.

For example:

```tsx
const el = document.createElement('ion-alert-controller');

 // This fails because componentOnReady not defined
el.componentOnReady(...);
```

When I look at the meta data in the `app.js` file it looks like it does not contain a definition for `ion-alert-controller`.  This results in the `HTMLElement` that is created never becoming a component and the Stencil methods not being defined.

If I include `<ion-alert-controller />` in other JSX code then it does get included in the build output.

**Expected behavior:**
Either the automatic bundle generation code should detect when components are being used in this way or there should be some standard way to Indicate to Stencil that a component is needed.

**Comment by mattdsteele** [comment]
I'm seeing something similar; though it's in a moderately complex app and I don't have a simple test case put together. Do you have a repository we can use to reproduce?

**Comment by adamdbradley** [comment]
Can you try running `npm run build --stats`, and a `stencil-stats.json` file will be created. Is ion-alert-controller not in there? How are you referencing ion-alert-controller?

**Comment by cjorasch** [comment]
Execute this code in starter app:

```tsx
const el = document.createElement('ion-alert-controller');
(el as any).componentOnReady();
```

This works with `0.3.0`.

With `0.4.0` the following error occurs:

```
TypeError: el.componentOnReady is not a function
```

**Comment by cjorasch** [comment]
Added 2 lines of code (above) to starter app in app-home render.  

Running `nom run build --stats` results in:

```
> @stencil/starter@0.0.1 build /Users/cjorasch/Projects/stencil-test-1
> stencil build --prerender

[36:09.4]  @stencil/core v0.4.0 💎
[36:09.5]  build, app, prod mode, started ...
[36:09.5]  compile started ...
[36:11.6]  compile finished in 2.07 s
[36:12.0]  generate bundles started ...
[36:12.7]  generate bundles finished in 686 ms
[36:12.7]  generate app files started ...
[36:13.9]  generate app files finished in 1.25 s
[36:13.9]  prerendering started ...
[36:13.9]  prerender, started: / ...
[36:14.9]  prerender, finished: / in 1.00 s

[ ERROR ]  Runtime error detected during componentWillLoad(): stencil-route
           matchPath is not defined ReferenceError: matchPath is not defined at t.computeMatch
           (evalmachine.<anonymous>:2:353) at t.componentWillLoad (evalmachine.<anonymous>:2:770) at update
           (/Users/cjorasch/Projects/stencil-test-1/node_modules/@stencil/core/dist/compiler/index.js:10737:53) at
           plt.queue.add
           (/Users/cjorasch/Projects/stencil-test-1/node_modules/@stencil/core/dist/compiler/index.js:10703:13) at flush
           (/Users/cjorasch/Projects/stencil-test-1/node_modules/@stencil/core/dist/compiler/index.js:11309:36) at
           _combinedTickCallback (internal/process/next_tick.js:131:7) at process._tickCallback
           (internal/process/next_tick.js:180:9)

[ ERROR ]  Runtime error detected during componentWillLoad(): stencil-route
           matchPath is not defined ReferenceError: matchPath is not defined at t.computeMatch
           (evalmachine.<anonymous>:2:353) at t.componentWillLoad (evalmachine.<anonymous>:2:770) at update
           (/Users/cjorasch/Projects/stencil-test-1/node_modules/@stencil/core/dist/compiler/index.js:10737:53) at
           plt.queue.add
           (/Users/cjorasch/Projects/stencil-test-1/node_modules/@stencil/core/dist/compiler/index.js:10703:13) at flush
           (/Users/cjorasch/Projects/stencil-test-1/node_modules/@stencil/core/dist/compiler/index.js:11309:36) at
           _combinedTickCallback (internal/process/next_tick.js:131:7) at process._tickCallback
           (internal/process/next_tick.js:180:9)

[36:15.0]  prerendered urls: 1 in 1.05 s
[36:15.0]  generate service worker started ...
[36:15.3]  generate service worker finished in 282 ms
[36:15.3]  build finished in 5.82 s
```

stencil.stats.json

```json
{
  "compiler": {
    "name": "@stencil/core",
    "version": "0.4.0"
  },
  "app": {
    "namespace": "App",
    "fsNamespace": "app",
    "components": 6,
    "entries": 3,
    "bundles": 6
  },
  "options": {
    "generateWWW": true,
    "generateDistribution": false,
    "minifyJs": true,
    "minifyCss": true,
    "hashFileNames": true,
    "hashedFileNameLength": 8,
    "buildEs5": true
  },
  "components": [
    {
      "tag": "app-profile",
      "dependencies": [],
      "dependencyOf": []
    },
    {
      "tag": "stencil-route",
      "dependencies": [],
      "dependencyOf": [
        "my-app"
      ]
    },
    {
      "tag": "stencil-router",
      "dependencies": [],
      "dependencyOf": [
        "my-app"
      ]
    },
    {
      "tag": "my-app",
      "dependencies": [
        "stencil-route",
        "stencil-router"
      ],
      "dependencyOf": []
    },
    {
      "tag": "stencil-route-link",
      "dependencies": [
        "stencil-route-link"
      ],
      "dependencyOf": [
        "app-home",
        "stencil-route-link"
      ]
    },
    {
      "tag": "app-home",
      "dependencies": [
        "stencil-route-link"
      ],
      "dependencyOf": []
    }
  ],
  "entries": [
    {
      "entryId": "entry:app-profile",
      "components": [
        {
          "tag": "app-profile",
          "dependencies": [],
          "dependencyOf": []
        }
      ],
      "bundles": [
        {
          "fileName": "nkzoukxb.js",
          "size": 448,
          "outputs": []
        },
        {
          "fileName": "nkzoukxb.es5.js",
          "size": 786,
          "outputs": [],
          "target": "es5"
        }
      ],
      "input": [
        {
          "filePath": "dist/collection/components/app-profile/app-profile.js"
        }
      ],
      "encapsulations": [
        "none"
      ]
    },
    {
      "entryId": "entry:my-app.stencil-route.stencil-router",
      "components": [
        {
          "tag": "stencil-route",
          "dependencies": [],
          "dependencyOf": [
            "my-app"
          ]
        },
        {
          "tag": "stencil-router",
          "dependencies": [],
          "dependencyOf": [
            "my-app"
          ]
        },
        {
          "tag": "my-app",
          "dependencies": [
            "stencil-route",
            "stencil-router"
          ],
          "dependencyOf": []
        }
      ],
      "bundles": [
        {
          "fileName": "ru4zffpg.js",
          "size": 9865,
          "outputs": []
        },
        {
          "fileName": "ru4zffpg.es5.js",
          "size": 10240,
          "outputs": [],
          "target": "es5"
        }
      ],
      "input": [
        {
          "filePath": "dist/collection/components/my-app/my-app.js"
        },
        {
          "filePath": "node_modules/@stencil/router/dist/collection/components/route/route.js"
        },
        {
          "filePath": "node_modules/@stencil/router/dist/collection/components/router/router.js"
        }
      ],
      "encapsulations": [
        "none"
      ]
    },
    {
      "entryId": "entry:app-home.stencil-route-link",
      "components": [
        {
          "tag": "stencil-route-link",
          "dependencies": [
            "stencil-route-link"
          ],
          "dependencyOf": [
            "app-home",
            "stencil-route-link"
          ]
        },
        {
          "tag": "app-home",
          "dependencies": [
            "stencil-route-link"
          ],
          "dependencyOf": []
        }
      ],
      "bundles": [
        {
          "fileName": "akrj4khp.js",
          "size": 2398,
          "outputs": []
        },
        {
          "fileName": "akrj4khp.es5.js",
          "size": 2918,
          "outputs": [],
          "target": "es5"
        }
      ],
      "input": [
        {
          "filePath": "dist/collection/components/app-home/app-home.js"
        },
        {
          "filePath": "node_modules/@stencil/router/dist/collection/components/route-link/route-link.js"
        }
      ],
      "encapsulations": [
        "none"
      ]
    }
  ]
}

```

**Comment by jthoms1** [comment]
@cjorasch Can you try installing `@stencil/router@next`. I pushed an update to workaround a rollup issue last night. (ie the matchPath error)

**Comment by cjorasch** [comment]
@jthoms1 Updated to `@stencil/router@next`.  Build output below.  Same runtime error.

```
> @stencil/starter@0.0.1 build /Users/cjorasch/Projects/stencil-test-1
> stencil build --prerender

[47:17.7]  @stencil/core v0.4.0 💎
[47:17.7]  build, app, prod mode, started ...
[47:17.8]  compile started ...
[47:20.1]  compile finished in 2.25 s
[47:20.4]  generate bundles started ...
[47:21.2]  generate bundles finished in 843 ms
[47:21.2]  generate app files started ...
[47:21.3]  generate app files finished in 57 ms
[47:21.3]  prerendering started ...
[47:21.3]  prerender, started: / ...
[47:21.8]  prerender, finished: / in 504 ms

[ ERROR ]  Runtime error detected while rendering: app-home
           t.componentOnReady is not a function TypeError: t.componentOnReady is not a function at t.render
           (evalmachine.<anonymous>:2:1897) at render
           (/Users/cjorasch/Projects/stencil-test-1/node_modules/@stencil/core/dist/compiler/index.js:10638:63) at
           renderUpdate
           (/Users/cjorasch/Projects/stencil-test-1/node_modules/@stencil/core/dist/compiler/index.js:10776:5) at update
           (/Users/cjorasch/Projects/stencil-test-1/node_modules/@stencil/core/dist/compiler/index.js:10769:13) at
           plt.queue.add
           (/Users/cjorasch/Projects/stencil-test-1/node_modules/@stencil/core/dist/compiler/index.js:10703:13) at flush
           (/Users/cjorasch/Projects/stencil-test-1/node_modules/@stencil/core/dist/compiler/index.js:11309:36) at
           _combinedTickCallback (internal/process/next_tick.js:131:7) at process._tickCallback
           (internal/process/next_tick.js:180:9)

[ ERROR ]  Cannot read property 'window' of null TypeError: Cannot read property 'window' of null at Object.destroy
           (/Users/cjorasch/Projects/stencil-test-1/node_modules/@stencil/core/dist/sys/node/index.js:597:17) at
           /Users/cjorasch/Projects/stencil-test-1/node_modules/@stencil/core/dist/compiler/index.js:12899:21 at
           Generator.next (<anonymous>) at fulfilled
           (/Users/cjorasch/Projects/stencil-test-1/node_modules/@stencil/core/dist/compiler/index.js:12836:58) at
           <anonymous> at process._tickCallback (internal/process/next_tick.js:188:7)
[47:21.8]  prerendered urls: 1 in 542 ms
[47:21.9]  generate service worker started ...
[47:22.0]  generate service worker finished in 144 ms
[47:22.0]  build finished in 4.27 s
```

**Comment by cjorasch** [comment]
Example repo uploaded to:

https://github.com/cjorasch/stencil-test-1

**Comment by jthoms1** [comment]
Ok this is a different error. My assumption is that this is in the automatic discovery process.

**Comment by adamdbradley** [comment]
When writing ```const el = document.createElement('ion-alert-controller');
(el as any).componentOnReady();```

Where is that text and in what file?

**Comment by cjorasch** [comment]
app-home.tsx

https://github.com/cjorasch/stencil-test-1/blob/master/src/components/app-home/app-home.tsx

**Comment by adamdbradley** [comment]
The demo is missing `@ionic/core` as a collection, so the compiler is unaware of what `ion-alert-controller` is. So if it doesn't find it then it's not in the registry of possible components that can load.

**Comment by adamdbradley** [comment]
Thanks again @cjorasch! Great find, should be fixed in the next release, thanks!

**Comment by cjorasch** [comment]
I tried to verify with the new version but got this error:

```
[56:29.4]  @stencil/core v0.4.2 💎
[56:29.5]  build, app, dev mode, started ...
[56:29.8]  compile started ...
[56:37.1]  compile finished in 7.30 s

[ ERROR ]  RangeError: Maximum call stack size exceeded at moduleGraph.importPaths.forEach.importPath
           (/Users/cjorasch/Projects/Meetings2/client4/node_modules/@stencil/core/dist/compiler/index.js:14190:45) at
           Array.forEach (<anonymous>) at getComponentDepsFromImports
           (/Users/cjorasch/Projects/Meetings2/client4/node_modules/@stencil/core/dist/compiler/index.js:14189:29) at
           moduleGraph.importPaths.forEach.importPath
           (/Users/cjorasch/Projects/Meetings2/client4/node_modules/@stencil/core/dist/compiler/index.js:14199:13) at
           Array.forEach (<anonymous>) at getComponentDepsFromImports
           (/Users/cjorasch/Projects/Meetings2/client4/node_modules/@stencil/core/dist/compiler/index.js:14189:29) at
           moduleGraph.importPaths.forEach.importPath
           (/Users/cjorasch/Projects/Meetings2/client4/node_modules/@stencil/core/dist/compiler/index.js:14199:13) at
           Array.forEach (<anonymous>) at getComponentDepsFromImports
           (/Users/cjorasch/Projects/Meetings2/client4/node_modules/@stencil/core/dist/compiler/index.js:14189:29) at
           moduleGraph.importPaths.forEach.importPath
           (/Users/cjorasch/Projects/Meetings2/client4/node_modules/@stencil/core/dist/compiler/index.js:14199:13)

[56:37.3]  build failed, watching for changes... in 7.80 s
```

I will try to come up with a simplified case because it is in a big project.

**Comment by adamdbradley** [comment]
Probably a circular dependency, which is perfectly fine to have but stencil isn't handling it well. I'll take a look quick. Thanks
