### PR TITLE
chore(test): migrate Karma tests to WebdriverIO

### PR DESCRIPTION
**Pull request by christian-bromann**
This patch migrates:

- [custom-elements-delegates-focus](https://github.com/ionic-team/stencil/blob/b4230b6939b016299d78cc4d16c175e73c703733/test/karma/test-app/custom-elements-delegates-focus)
- [custom-elements-output-tag-class-different](https://github.com/ionic-team/stencil/blob/b4230b6939b016299d78cc4d16c175e73c703733/test/karma/test-app/custom-elements-output-tag-class-different)
- [custom-elements-output-webpack](https://github.com/ionic-team/stencil/blob/b4230b6939b016299d78cc4d16c175e73c703733/test/karma/test-app/custom-elements-output-webpack)

### CODE REVIEW

File: test/karma/test-app/custom-elements-output-webpack/webpack.config.js [hunk 1]
```diff
@@ -1,20 +0,0 @@
-const path = require('path');
-const { WWW_OUT_DIR } = require('../../constants');
-
-module.exports = {
-  entry: path.resolve(__dirname, 'index.esm.js'),
```
Comment (christian-bromann) [inline test/karma/test-app/custom-elements-output-webpack/webpack.config.js:5]: Does someone know the point of having Webpack involved here? It doesn't seem to do anything other than re-bundling the package and importing it in the browser. I believe we cover this feature with the [setup script](https://github.com/ionic-team/stencil/blob/908f7780f5979beeb99a4b5f0aedb626590a8ec8/test/wdio/setup.ts) automatically.

Comment (alicewriteswrongs) [reply test/karma/test-app/custom-elements-output-webpack/webpack.config.js:5]: I think @rwaskiewicz is familiar with the basis for the setup -- if it's possible for us to do without it I'm all for it because it's super confusing haha

**Review by alicewriteswrongs — APPROVED** [review]

**Comment by tanner-reits** [comment]
@christian-bromann looks like there are some CI failures

**Comment by christian-bromann** [comment]
> looks like there are some CI failures

Addressed them, they sneaked it after the last rebase

File: test/karma/test-app/custom-elements-output-webpack/webpack.config.js (hunk 1 above)
Comment (rwaskiewicz) [reply test/karma/test-app/custom-elements-output-webpack/webpack.config.js:5]: IIRC, reason for this was two-fold:
1. to test Stencil could go through the webpack process (this is a regression Stencil had at some point)
2. To use the `dist-custom-elements` output target, as opposed to `www`

File: test/wdio/package-lock.json [hunk 2]
```diff
@@ -23,8 +23,7 @@
       }
     },
     "../..": {
-      "name": "@stencil/core",
```
[the remark this answers is not in the document]
Comment (christian-bromann) [reply test/wdio/package-lock.json]: not sure how this slipped in

**Comment by christian-bromann** [comment]
> Some of these tests were built specifically for DCE or Webpack regressions/features - with that in mind, I think there's some value in bringing them back.

@rwaskiewicz I tracked down the source of the test which was introduced in https://github.com/ionic-team/stencil/pull/3039. From what I can see is that this verifies that the DCE output target provides a `defineCustomElement` method to register the custom element. I would suggest to tweak the setup script to __not__ run for this test and have the component imported and registered manually and verify that the component can be initialized properly.

I don't think it makes sense anymore to keep Webpack as a dependency for this test stack.

**Comment by christian-bromann** [comment]
> I think I'd be amenable to that 👍

I made changes accordingly. Let me know what you think.

**Review by alicewriteswrongs — APPROVED** [review]

File: test/wdio/slot-reorder/cmp.test.tsx [hunk 3]
```diff
@@ -131,21 +131,21 @@ describe('slot-reorder', () => {
...
-    await browser.waitUntil(() => {
+    await browser.waitUntil(async () => {
       return !document.querySelector('div.reordered');
     });
 
     ordered();
 
     await $('button').click();
-    await browser.waitUntil(() => {
+    await browser.waitUntil(async () => {
```
Comment (rwaskiewicz) [inline test/wdio/slot-reorder/cmp.test.tsx:148]: Does passing an `async` function to `waitUntil` do anything special? Or do we not need these `async` fns?

**Review by rwaskiewicz — APPROVED** [review]
One non-blocking question

File: test/wdio/slot-reorder/cmp.test.tsx (hunk 3 above)
Comment (christian-bromann) [reply test/wdio/slot-reorder/cmp.test.tsx:148]: I've seen race conditions saying `.then is not a function` and my assumptions are that this has to do with WebdriverIO. It is on the list of things I'ld like to look into eventually. In the meeting, I am adding this to avoid the race conditions.
