### ISSUE TITLE
Starter app doesn't install @stencil/router on windows.

### ISSUE THREAD

**Issue by andylockran** [ionic-team/stencil#100]
When running the 'Getting started' example from stencilJS - it errors out on windows with the following error:
```
$ npm start

> @stencil/starter@0.0.1 start C:\Users\aloughran\Documents\Code\Stencil\my-app
> npm run dev


> @stencil/starter@0.0.1 dev C:\Users\aloughran\Documents\Code\Stencil\my-app
> sd concurrent "stencil build --dev --watch" "stencil-dev-server"

events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::3333
    at Object.exports._errnoException (util.js:1016:11)
    at exports._exceptionWithHostPort (util.js:1039:20)
    at Server.setupListenHandle [as _listen2] (net.js:1307:14)
    at listenInCluster (net.js:1355:12)
    at Server.listen (net.js:1455:7)
    at Object.<anonymous> (C:\Users\aloughran\Documents\Code\Stencil\my-app\node_modules\@stencil\dev-server\dist\index.js:84:64)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\aloughran\Documents\Code\Stencil\my-app\node_modules\@stencil\dev-server\dist\index.js:4:58)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:169:7)
[49:33.2]  build, dev mode, started ...
[49:33.2]  compile started ...
[49:34.8]  compile finished in 1.61 s

[ ERROR ]  Cannot find module '@stencil/router' at Function.Module._resolveFilename (module.js:485:15) at
           Object.resolveModule
           (C:\Users\aloughran\Documents\Code\Stencil\my-app\node_modules\@stencil\core\bin\sys.js:135:22) at
           loadDependentManifest
           (C:\Users\aloughran\Documents\Code\Stencil\my-app\node_modules\@stencil\core\dist\compiler\index.js:5416:62)
           at C:\Users\aloughran\Documents\Code\Stencil\my-app\node_modules\@stencil\core\dist\compiler\index.js:5407:16
           at Array.map (native) at loadDependentManifests
           (C:\Users\aloughran\Documents\Code\Stencil\my-app\node_modules\@stencil\core\dist\compiler\index.js:5406:43)
           at C:\Users\aloughran\Documents\Code\Stencil\my-app\node_modules\@stencil\core\dist\compiler\index.js:5512:16
           at <anonymous>

[49:34.9]  build failed, watching for changes... in 1.69 s
```

Running `npm install @stencil/router --save` resolves the problem, but should this be pulled in directly from the base package.json, rather than being an additional step/explicit dependency?

**Comment by john-landgrave** [comment]
Just a thought @andylockran, it looks like you're already running something on port 3333, have you tried correcting that issue first? I agree that the error message "Cannot find module" sounds like it's missing, but we all know that npm sometimes isn't great about error messages.

Also, are you running up-to-date node and npm? I've noticed some weirdness before with different versions since the big npm v5 update ([more on that here](http://www.infoworld.com/article/3198746/javascript/npm-5-reworks-the-cache-for-speed-but-will-break-with-older-code.html))

**Comment by DavidBernal** [comment]
Same problem with node 8.0 and 8.4.
Works with node 6.11

**Comment by jgw96** [comment]
@DavidBernal and @andylockran  , what version of `npm` are yall running? Im running node 8.2.1 and npm 5.3 and am not able to reproduce this issue on my surface book running the latest stable build of windows 10

**Comment by jgw96** [comment]
Hello everyone! I am going to be closing this issue for now as it has been a while since there was any activity, but i would recommend making sure you're running the latest version of npm 5 (or downgrading to npm 4), deleting your `package-lock.json` file and re-installing. Thanks!

**Comment by darksnake747** [comment]
Hey everyone! Just wanted to share my info on this topic.

I ran through the steps to setup the starter app. Everything seemed okay after the instructed steps, but when I'd try to build the app via `npm run build`, I was getting an error stating:

```
Cannot find module 'resolve' at Function.Module._resolveFilename (module.js:547:15) at Function.Module._load
           (module.js:474:25) at Module.require (module.js:596:17) at require (internal/module.js:11:18) at
           Object.<anonymous>
```

Being new to Node/NPM/Stencil, I didn't really know what to do but noticed the issue seemed to be within the packages... and I had noticed a few more npm notices than normal when I first ran the install. So, I decided to simply try to *maybe fix* those packages with an `npm update`. After running that, I found that my build actually worked! So, hopefully this helps someone.

I am using:
Windows 10
Node 8.11.1
NPM 5.6.0
Stencil 0.7.24

- cheers -

**Comment by lautaros86** [comment]
Hi, I have the same problem.

PS D:\workspace\pruebas\my-component> npm start

> my-component@0.0.1 start D:\workspace\pruebas\my-component
> npm run dev


> my-component@0.0.1 dev D:\workspace\pruebas\my-component
> sd concurrent "stencil build --dev --watch" "stencil-dev-server"

[49:31.1]  @stencil/core v0.7.22
[49:31.1]  build, mycomponent, dev mode, started ...
[49:31.2]  compile started ...
[49:33.4]  compile finished in 2.28 s

[ ERROR ]  typescript: D:/workspace/pruebas/my-component/node_modules/@types/jest/index.d.ts, line: 15
           Duplicate identifier 'beforeAll'.

     L14:  declare const expect: jest.Expect;
     L16:  interface NodeRequire {

[ ERROR ]  typescript: D:/workspace/pruebas/my-component/node_modules/@types/jest/index.d.ts, line: 16
           Duplicate identifier 'beforeEach'.

     L16:  interface NodeRequire {

[ ERROR ]  typescript: D:/workspace/pruebas/my-component/node_modules/@types/jest/index.d.ts, line: 17
           Duplicate identifier 'afterAll'.

     L16:  interface NodeRequire {
     L18:       * Returns the actual module instead of a mock, bypassing all checks on

[ ERROR ]  typescript: D:/workspace/pruebas/my-component/node_modules/@types/jest/index.d.ts, line: 18
           Duplicate identifier 'afterEach'.

     L18:   * Returns the actual module instead of a mock, bypassing all checks on
     L19:   * whether the module should receive a mock implementation or not.

[ ERROR ]  typescript: D:/workspace/pruebas/my-component/node_modules/@types/jest/index.d.ts, line: 19
           Duplicate identifier 'describe'.

     L18:  * Returns the actual module instead of a mock, bypassing all checks on
     L19:  * whether the module should receive a mock implementation or not.

[ ERROR ]  typescript: D:/workspace/pruebas/my-component/node_modules/@types/jest/index.d.ts, line: 20
           Duplicate identifier 'fdescribe'.

     L19:   * whether the module should receive a mock implementation or not.
     L21:  requireActual(moduleName: string): any;

[ ERROR ]  typescript: D:/workspace/pruebas/my-component/node_modules/@types/jest/index.d.ts, line: 21
           Duplicate identifier 'xdescribe'.

     L21:  requireActual(moduleName: string): any;

[ ERROR ]  typescript: D:/workspace/pruebas/my-component/node_modules/@types/jest/index.d.ts, line: 22
           Duplicate identifier 'it'.

     L21:  requireActual(moduleName: string): any;
     L23:   * Returns a mock module instead of the actual module, bypassing all checks

[ ERROR ]  typescript: D:/workspace/pruebas/my-component/node_modules/@types/jest/index.d.ts, line: 23
           Duplicate identifier 'fit'.

     L23:   * Returns a mock module instead of the actual module, bypassing all checks
     L24:   * on whether the module should be required normally or not.

[ ERROR ]  typescript: D:/workspace/pruebas/my-component/node_modules/@types/jest/index.d.ts, line: 24
           Duplicate identifier 'xit'.

     L23:  * Returns a mock module instead of the actual module, bypassing all checks
     L24:  * on whether the module should be required normally or not.

[ ERROR ]  typescript: D:/workspace/pruebas/my-component/node_modules/@types/jest/index.d.ts, line: 28
           Cannot redeclare block-scoped variable 'expect'.

     L29:  declare namespace jest {

[ ERROR ]  typescript: D:/workspace/pruebas/my-component/node_modules/@types/jest/index.d.ts, line: 558
           Cannot redeclare block-scoped variable 'DEFAULT_TIMEOUT_INTERVAL'.

    L558:      interface Clock {
    L559:          install(): void;

[ ERROR ]  typescript: D:/workspace/pruebas/my-component/node_modules/@types/jest/index.d.ts, line: 559
           Duplicate identifier 'clock'.

    L558:  interface Clock {
    L559:      install(): void;
    L560:      uninstall(): void;

[ ERROR ]  typescript: D:/workspace/pruebas/my-component/node_modules/@types/jest/index.d.ts, line: 706
           Duplicate identifier 'CustomMatcherFactory'.

    L707:      interface CustomMatcherResult {

[ ERROR ]  typescript: D:/workspace/pruebas/my-component/node_modules/@types/jest/index.d.ts, line: 714
           Duplicate identifier 'CustomEqualityTester'.

    L713:      length: number;
    L714:      [n: number]: T;

[49:33.4]  build failed, watching for changes... in 2.31 s

I am using:
Windows 10
Node 8.11.1
NPM 5.6.0
