### ISSUE TITLE
bug: upgrading stencil to 2.13.0 test cases failing 

### ISSUE THREAD

**Issue by rahul-rautwar** [ionic-team/stencil#3274]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/stencil/blob/main/.github/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/ionic-team/stencil/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/ionic-team/stencil/issues) that already report this problem, without success.

### Stencil Version

2.13.0

### Current Behavior

After upgrading the stencil from **2.12.1 to 2.13.0** test cases failing.

yarn build and yarn start command working fine.
But when trying to run test cases using 'yarn run unit:ci' test cases are failing.

"@stencil/core": "2.13.0",
    "@stencil/angular-output-target": "0.3.0",
    "@stencil/react-output-target": "0.0.9",
    "@stencil/vue-output-target": "^0.5.1",
    "@stencil/sass": "^1.4.1",
    "@stencil/utils": "^0.0.5",
    "@types/jest": "^27.0.3",
"jest": "^27.4.5",
"jest-cli": "^27.4.5",
"jest-environment-node": "27.5.1",

Getting below error for failed test cases:

` ● Timepicker Functional Suite › should check for auto decrement in hour value when manageMinute is called and having threshold value

    TypeError: e.dispatchEvent is not a function
      at emitEvent (../../node_modules/@stencil/core/internal/testing/index.js:494:12)
      at Object.emit (../../node_modules/@stencil/core/internal/testing/index.js:1185:168)
      at Timepicker.updateEventData (src/components/dxp-timepicker/dxp-timepicker.tsx:3070:15)
      at Timepicker.manageHour (src/components/dxp-timepicker/dxp-timepicker.tsx:2960:10)
      at Timepicker.manageMinute (src/components/dxp-timepicker/dxp-timepicker.tsx:3006:16)
      at Object.<anonymous> (src/components/dxp-timepicker/dxp-timepicker.spec.ts:140:16)`
      
`● Navigation › should remove active attribute on click and will add active link function 

    ReferenceError: document is not defined

       98 |   });
       99 |   it('should remove active attribute on click and will add active link function ', async () => {
    > 100 |     const elemNav = document.createElement('nav');
          |                     ^
      101 |     const elem = document.createElement('dxp-nav-group');
      102 |     const demoTagChildAnchor = document.createElement('a');
      103 |     const div = document.createElement('div');

      at Object.<anonymous> (src/components/dxp-navigation/common-utility.spec.ts:100:21)`

`  ● Test suite failed to run

    Call retries were exceeded

      at ChildProcessWorker.initialize (../../node_modules/jest-runner/node_modules/jest-worker/build/workers/ChildProcessWorker.js:193:21)

FAIL src/components/dxp-checkbox-tree/dxp-checkbox-tree.spec.ts
  ● Test suite failed to run

    Call retries were exceeded

      at ChildProcessWorker.initialize (../../node_modules/jest-runner/node_modules/jest-worker/build/workers/ChildProcessWorker.js:193:21)

Test Suites: 122 failed, 57 passed, 179 of 260 total
Tests:       410 failed, 11 skipped, 3788 passed, 4209 total`
    

### Expected Behavior

Test cases and Test Suites should not failed.

As per the blog from Ryan, it does not require any project to upgrade their version of Jest at this time. [Blog URL](https://ionicframework.com/blog/stencil-jest-27-upgrade-instructions/?_gl=1*nv233g*_ga*MjEwNTc5OTMwMS4xNjQ2ODI4NTgw*_ga_REH9TJF6KF*MTY0NjkwNjc3NC4yLjAuMTY0NjkwNjc3NC4w)

### Steps to Reproduce

Upgrading to stencil 2.13.0 and running 'yarn run unit:ci'

### Code Reproduction URL

NA

**Comment by rwaskiewicz** [comment]
👋 

@rahul-rautwar would you be able to create a minimal code reproduction URL for us? Unfortunately it's hard to see what's happening here without being about to see the code, associated configuration files, etc.  Thanks!
