### ISSUE TITLE
bug: Hydrate runtime crashes with external SSR DOMs that do not implement `attachShadow` (Angular SSR + Domino)

### ISSUE THREAD

**Issue by SebastianKohler** [ionic-team/stencil#6605]
### Prerequisites

- [x] I have read the [Contributing Guidelines](https://github.com/stenciljs/core/blob/main/CONTRIBUTING.md).
- [x] I agree to follow the [Code of Conduct](https://github.com/stenciljs/core/blob/main/CODE_OF_CONDUCT.md).
- [x] I have searched for [existing issues](https://github.com/stenciljs/core/issues) that already report this problem, without success.

### Stencil Version

4.x (bundled hydrate runtime in `@ionic/core`; exact Stencil build version of shipped bundle not directly exposed)

### Current Behavior

In Stencil hydrate runtime, shadow component hydration can crash on server-side DOM implementations that do not provide native `attachShadow` (e.g. Domino).

The crash occurs in the hydrate path (as seen in runtime output / source-mapped comments): [`proxyHostElement`](https://github.com/stenciljs/core/blob/main/src/hydrate/platform/proxy-host-element.ts) -> [`createShadowRoot`](https://github.com/stenciljs/core/blob/main/src/utils/shadow-root.ts) -> `this.attachShadow(...)`.

When `elm.attachShadow` is missing, SSR throws:

```txt
TypeError: this.attachShadow is not a function
    at createShadowRoot ...
    at proxyHostElement ...
```

Concrete scenario where we reproduce this consistently: Angular SSR (`@angular/ssr`) + Ionic web components (`@ionic/core` hydrate path).

So the repro app is Angular SSR + Ionic, but the failure is in Stencil hydrate internals above.

### Expected Behavior

Stencil hydrate should not throw when running against server-side DOMs where `attachShadow` is unavailable on host elements (e.g. Domino).

Instead, runtime should follow an SSR-safe path (fallback or graceful skip for shadow-root creation) so hydration can continue and complete without crashing the SSR request.

### System Info

```shell
- OS: Windows 11 (also reported by others on non-Windows)
- Node: 22.x
- Angular SSR: 20.3.x (`@angular/ssr`, `CommonEngine`)
- Ionic: works on `8.2.2`, fails on newer 8.x (e.g. `8.7.17`)
- Regression window (observed via shipped `@ionic/core` hydrate behavior): `@ionic/core@8.2.2` works, `@ionic/core@8.7.17` fails with `attachShadow` error.
```

### Steps to Reproduce

1. Clone repro: <https://github.com/SebastianKohler/ionic-angular-ssr-attachShadow-typeError>.
2. Install dependencies: `npm install`.
3. Use failing Ionic version (default in repo, e.g. `8.7.17`).
4. Build SSR bundles: `npm run build:ssr`.
5. Start SSR server: `npm run serve:ssr`.
6. Open <http://localhost:4000/>.
7. Observe server crash with `TypeError: this.attachShadow is not a function` when Ionic components are present.
8. (Verification) Pin `@ionic/angular`, `@ionic/angular-server`, and `@ionic/core` to `8.2.2`, reinstall, repeat steps 4–6: crash disappears. Note: this is true even if the consuming app resolves a newer top-level `@stencil/core` (e.g. `4.43.0`), which indicates the behavior is tied to the hydrate bundle shipped in `@ionic/core`, not the app’s installed `@stencil/core` package version.

### Code Reproduction URL

https://github.com/SebastianKohler/ionic-angular-ssr-attachShadow-typeError

### Additional Information

The bug has also been reported to Ionic: <https://github.com/ionic-team/ionic-framework/issues/29751>

As seen in the comments there, multiple users are affected.

**Comment by johnjenkins** [comment]
hi @SebastianKohler - thanks for raising!
Apologies but I think there's just a few too many moving parts to diagnose this issue for a one person 'team' :D 

I am tempted to say this isn't _really_ Stencil's fault though - Stencil's hydrate script is designed to render it's components within it's own `mock-doc` environment and `mock-doc` defines `attachShadow` on it's node proto ([here](https://github.com/stenciljs/core/blob/main/src/mock-doc/node.ts#L279)) < this is required to render the components using [Declarative Shadow DOM](https://web.dev/articles/declarative-shadow-dom) (My guess is *this* is the difference in breaking ionic versions < Stencil starting shipping / supporting DSD).

I think what is happening, is that the ionic / angular-server combo *does not* use mock-doc to render the components, rather they pass in Angular's own 'DOM' environment ([here](https://github.com/ionic-team/ionic-framework/blob/682a17ebb754da7714989623cf84b75e715e20e1/packages/angular-server/src/ionic-server-module.ts#L20)) which doesn't support `attachShadow`. 

The fix that ionic could ship today (without any Stencil change) would be to *not* render their components using DSD, rather use the old behaviour ("scoped") > [read more here](https://stenciljs.com/docs/hydrate-app#serializeshadowroot) 

A longer term / more robust Stencil change would be for Stencil to check for `attachShadow` and if not available create `documentFragment` and assign it to the instance `this.shadowRoot` - this *should* serialize to DSD in the same way... I would think you might be able patch the Angular DOM solution to do that as another potential fix(?)

**Comment by SebastianKohler** [comment]
Thanks for taking a look, and for the extra context.

I created a minimal repro that removes both Angular and Ionic, so this is now just Stencil hydrate + Domino:

Repo: <https://github.com/SebastianKohler/stencil-attachshadow-domino-repro>

Repro:

```bash
corepack pnpm install
corepack pnpm run repro:attach-shadow
```

Result:

- `host.attachShadow exists: undefined`
- hydrate reports `TypeError: this.attachShadow is not a function`
- stack path goes through hydrate internals (`proxyHostElement` -> `createShadowRoot`)

So this reproduces the same core failure mode independently of Ionic/Angular.

I agree with your point that Ionic can likely mitigate this at integration level (for example using non-DSD/scoped behavior).
I mainly wanted to provide a minimal case for awareness and to clarify support expectations.

If helpful, here are the detailed steps I used:

---

Do this in a fork of `stencil-angular-starter`:

1. Edit `packages/stencil-lib/stencil.config.ts` and add hydrate output target:

```
{
  type: 'dist-hydrate-script',
},
```

2. Add `domino` to root `package.json` devDependencies:

```
"domino": "^2.1.6"
```

3. Add a root script in `package.json`:

```
"repro:attach-shadow": "corepack pnpm --filter @example/stencil-lib run build && node repro-domino-hydrate.mjs"
```

4. Create `repro-domino-hydrate.mjs` in repo root:

```javascript
import domino from 'domino';
import { hydrateDocument } from './packages/stencil-lib/hydrate/index.mjs';

const html = `
<!doctype html>
<html>
<head><meta charset="utf-8"></head>
<body>
  <example-input value="hello"></example-input>
</body>
</html>
`;

const window = domino.createWindow(html);
const doc = window.document;
const host = doc.querySelector('example-input');

console.log('host tag:', host?.tagName);
console.log('host.attachShadow exists:', typeof host?.attachShadow);

const result = await hydrateDocument(doc, { clientHydrateAnnotations: false });

const hasAttachShadowError = (result?.diagnostics ?? []).some((d) =>
String(d?.messageText ?? '').includes('attachShadow is not a function')
);

for (const d of result?.diagnostics ?? []) {
console.log('diagnostic:', d.type, d.level, d.messageText);
}

if (hasAttachShadowError) {
console.error('Reproduced: attachShadow error from Stencil hydrate runtime');
process.exit(1);
}
```

5. Run:

```bash
corepack pnpm install
corepack pnpm run repro:attach-shadow
```

Expected result:

- `host.attachShadow exists: undefined`
- diagnostic contains `TypeError: this.attachShadow is not a function`
- stack points into generated hydrate runtime (`createShadowRoot` -> `proxyHostElement`).

---

Question for clarity: is `hydrateDocument(...)` intended to work with non-mock-doc DOMs like Domino, or should this be treated as out of scope today?

If it’s out of scope, a clearer diagnostic/docs note would already be very helpful.

**Comment by johnjenkins** [comment]
Thanks for the confirmation / research. Super helpful!

> Question for clarity: is hydrateDocument(...) intended to work with non-mock-doc DOMs like Domino, or should this be treated as out of scope today?

> If it’s out of scope, a clearer diagnostic/docs note would already be very helpful.

Quite honestly, it's a use case I had never considered, but I would say it's probably out-of-scope for Stencil to support rendering environments that do not support the minimum specs required for modern custom elements (I notice Domino's last update was 6 years ago). If the environment in question was JSDOM or happy-dom for example then perhaps there would be a stronger case. Does that sound reasonable?

**Comment by SebastianKohler** [comment]
That sounds totally reasonable to me, thanks for clarifying the scope!

Would you be open to adding:

1. a docs note that `hydrateDocument(...)` expects a DOM with modern custom-element primitives (including `attachShadow`), and
2. a clearer diagnostic when that requirement is not met (instead of `this.attachShadow is not a function`)?

That would help integrators quickly identify unsupported SSR DOM environments.

I also tested an Ionic-side integration workaround using `serializeShadowRoot: 'scoped'`. It avoids the server `attachShadow` crash, but in my Angular SSR + Ionic setup it leads to incorrect client output (duplicate light-DOM internals, e.g. an extra `<button>` outside the shadow root after upgrade). So it’s not a viable final fix for this case.

I’ll continue this on the Ionic issue as an integration-level compatibility fix request.

**Comment by johnjenkins** [comment]
> Would you be open to adding ... a docs note that hydrateDocument(...)

Definitely open! I am very snowed under though, so PRs welcome! 

> ... a clearer diagnostic when 

Yep again - a try / catch around `this.attachShadow` with a more helpful error message < PRs welcome!

> It avoids the server attachShadow crash, but in my Angular SSR + Ionic setup it leads to incorrect client output (duplicate light-DOM internals, e.g. an extra <button> outside the shadow root after upgrade). So it’s not a viable final fix for this case.

^ Make sure to enable `clientHydrateAnnotations: true` < I noticed ionic have it as `false`

**Comment by SebastianKohler** [comment]
I tested with `clientHydrateAnnotations: true` as well, but unfortunately it did not resolve the issue in this repro.

Thanks again for the guidance and for taking the time to look into this.

**Comment by johnjenkins** [comment]
🙏 - thanks again for you time. 

> I tested with clientHydrateAnnotations: true as well, but unfortunately it did not resolve the issue in this repro.

I'd be interested to know if this is an issue with Domino or Stencil's re-hydration. If the latter, I would be keen to get it fixed

**Comment by SebastianKohler** [comment]
Follow-up with good news: this no longer looks like a Stencil scoped+annotations bug.

What I verified:

- `serializeShadowRoot: 'scoped'` + `clientHydrateAnnotations: true` produces expected SSR markers (`s-id`, `c-id`, `<!--r.*-->`) and rehydrates correctly (no duplicate internals).
- `scoped + annotations:false` reproduces the duplicate-internals shape.
- In Angular/Ionic, the remaining runtime error is:
`TypeError: Cannot read properties of undefined (reading 'hasAttribute')` and this disappears when `provideClientHydration()` is removed.

So the current remaining issue points to Angular/Ionic hydration integration, not Stencil rehydration correctness for scoped+annotations.

**Comment by johnjenkins** [comment]
> Follow-up with good news: this no longer looks like a Stencil scoped+annotations bug.

Good to know - sounds like progress!

> TypeError: Cannot read properties of undefined (reading 'hasAttribute') and this disappears when provideClientHydration() is removed.

I'd be interested to look at that if you have a repro; it still sounds like a potential thing Stencil might be able to help with - Angular isn't finding an `HTMLElement` where it expects so perhaps something is in a wrong position.

**Comment by SebastianKohler** [comment]
The Angular/Ionic repro app with the diagnostic patch is in a separate branch here: <https://github.com/SebastianKohler/ionic-angular-ssr-attachShadow-typeError/tree/scoped%2Bannotations-diagnostic-patch>

It has a patched `ionic-server-scoped.module.ts` with `clientHydrateAnnotations: true` and `serializeShadowRoot: 'scoped'` on `hydrateDocument()` as seen in this commit: https://github.com/SebastianKohler/ionic-angular-ssr-attachShadow-typeError/commit/a11b419f02a5939457a712b60d7a42e1f023153a

Run

```
npm run build:ssr
```

to build the SSR app and then

```
npm run serve:ssr
```

Open <http://localhost:4000/>.

**Comment by johnjenkins** [comment]
Ok - I can see the error .. 

The `ion-app` element returns no children atm -

<img width="464" height="518" alt="Image" src="https://github.com/user-attachments/assets/79256c0e-11db-4154-8662-89cdeee32f0a" />

(you can test this by removing the wrapping `<ion-app>` - no errors)

TLDR - This was due to Stencil's patching behaviour which was fixed in Stencil 4.40.0 (ionic is currently on 4.38.0)

Alternatively, if ionic were to just add a `<slot />` to the `ion-app` component, that would also work. 

<img width="831" height="678" alt="Image" src="https://github.com/user-attachments/assets/dad25d65-f0e9-4bdb-9a9f-70e5028d64b2" />


(more info if interested ....

Basically, for 'non-shadow' components (components with no shadowDOM encapsulation), Stencil optionally adds a few patches to shield the element's internal DOM from outside (this is often important when embedded within a framework).

In Ionic's version of Stencil, there was a bug whereby 'non-shadow' components that also do not use a `<slot />` would return nothing for `.children` and `.childNodes`.
)

**Comment by SebastianKohler** [comment]
Thanks a lot for digging into this, this is incredibly helpful!

Given your analysis, this sounds like a clear path on the Ionic side:
1. use `serializeShadowRoot: 'scoped'`
2. set `clientHydrateAnnotations: true`
3. update Ionic’s bundled Stencil runtime to `>= 4.40.0`

The `<slot />` in `ion-app` also makes sense as a workaround, but bumping the bundled Stencil version seems like the better fix direction.
