### ISSUE TITLE
Rollup can't find CSS sibling files for components when running in Bazel sandbox in Stencil >= 1.15.0

### ISSUE THREAD

**Issue by loudmouth** [ionic-team/stencil#2840]
**Stencil version:**

```
 @stencil/core >=1.15.0 (tested on newest releases as well 2.5.2)
```

**I'm submitting a:**

- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

This change only happens when upgrading from version 1.14.0 to version 1.15.0 and is affected at every version >= 1.15.0.
When running in a [Bazel](https://github.com/ionic-team/stencil/compare/v1.14.0...v1.15.0) sandbox, rollup is unable to resolve imports for the corresponding CSS file for a stencil component.

Say I have a component as the one pasted below, the build will work fine running directly via stencil, but then when executing through Bazel, Rollup says it can't resolve the import:
```
[ ERROR ]  Rollup: Unresolved Import
           Could not resolve './my-comp?tag=my-comp' from
           ./src/components/my-comp/my-comp.tsx at error
```
```tsx
import { Component, h, State } from '@stencil/core';

@Component({
  tag: "my-comp",
  styleUrl: "my-comp.css",
})
export class MyComp {
  render() {
    return (
      <Host>
        <slot></slot>
      </Host>
    );
  }
}
```

**Expected behavior:**
Rollup should find the files if they are located in the correct place. 

**Steps to reproduce:**

I have taken the time to [make an example repo](https://github.com/loudmouth/bazel-stencil) exemplifying the issue and have left run instructions there. The repo illustrates that everything works with 1.14.0 but not with 1.15.0 and above

https://github.com/loudmouth/bazel-stencil

Note that simply omitting component CSS all together, but continuing to include `globalStyle`, the build succeeds with all expected outputs, leading me to believe this is specific only to the way CSS files set via `styleUrls` are resolved 

**Related code:**

**Other information:**

I was reviewing the [changes from 1.14.0 to 1.15.0](https://github.com/ionic-team/stencil/compare/v1.14.0...v1.15.0) and was curious if possibly this issue could be due to a change in the way [CSS file paths are normalized](https://github.com/ionic-team/stencil/compare/v1.14.0...v1.15.0#diff-a90a836949139b0a395b6ecd00c565f300cdee1fbee4efe26f62bab55b1e6524R143).

(If that hyperlink doesn't work, it's in the diff from 1.14.0 to 1.15.0 at src/utils/normalize-path.ts, line 143)

**Comment by loudmouth** [comment]
This affects resolving any kind of style files by the way, (i.e. sass, scss, etc) and is not specific to the .css file extension

**Comment by loudmouth** [comment]
Actually, I think the issue could be with the way symlinks are resolved since in the bazel sandbox, the files are all symlinked

**Comment by loudmouth** [comment]
maybe this [commit](https://github.com/ionic-team/stencil/commit/0ea9c714ed9bb4cfb85492c0d9afbb92cf3c2985) (merged between 1.14.0 and 1.15.0 is where relevant code changed regarding resolving file paths (including symlinks)?

**Comment by loudmouth** [comment]
I would be happy to make a merge request to fix this issue, but would need a small bit of direction as I'm really not familiar with the codebase. I went through the effort of making a repo that reproduces the issue, and I'm quite confident I've even found the merge request where things broke.

Any chance this issue could get a small peek from the maintainers?

**Comment by loudmouth** [comment]
commenting to prevent autoclosure after 30 days.

**Comment by gonstr** [comment]
+1 would like to see this fixed

**Comment by loudmouth** [comment]
The changes in #2900 allow Rollup to resolve symlinked styles files while executing a build inside the Bazel sandbox. Bazel + Stencil together has facilitated a great workflow for our project, but we've been unable to take advantage of some new features such as the [@stencil/react-output-target](@stencil/react-output-target). Assuming the vision for Stencil still has the goal of facilitate builds with external build tools (as mentioned in [this Stencil blog post](https://stenciljs.com/blog/stencil-roadmap-fall-2019)), I am hoping we can get the change merged. 

As a side note: while I did include a custom Bazel rule for Stencil + Bazel in the repo for reproducing the issue, there is an alternative implementation which uses for Bazel rules_nodjes builtins to run Stencil builds. I would be happy to update with a Bazel built-in way of running stencil in dev-mode as well.

**Comment by tcarrio** [comment]
I have proposed a change in PR#2981 that will address this without any breaking changes to the spec. Hopefully this will move faster so we can start using Bazel with Stencil :raised_hands:

**Comment by splitinfinities** [comment]
I'd like to understand the current state of the art within the community working with a Monorepo. If you have any tips, tricks, concerns, or questions, please comment what you are bumping into and how/if you hack around it.

**Comment by splitinfinities** [comment]
Hey there, thank you for the patience getting back to you. The new team is getting started and we're working through the backlog now.

I'd like to understand the current state of the art within the community working with a Monorepo. If you have any tips, tricks, concerns, or questions, please comment what you are bumping into and how/if you hack around it.

Additionally, if this still happens on v2 of Stencil, please let me know and update this repo https://github.com/loudmouth/bazel-stencil.

**Comment by loudmouth** [comment]
Hey! Thanks for getting back to me!

I would be super interested in talking to the team more about Stencil + Bazel as my team and I have been doing it for several years: you could say we've grown up with both technologies. You can find me on the Stencil slack with the same name "loudmouth" and maybe we could talk more.

Anyway, I did indeed find a workaround that I was afraid of publicizing: I dug deep into Rollup (which was new for me) and found that I could write a plugin that overwrote all rollup config how I wanted. The reason I didn't want to publicize it, is because I've maintained open-source before, and had the fear in the back of my mind, that maybe you wouldn't want people being able to overwrite the entire config, and also since Stencil wasn't getting as much attention at the time, I was worried I could have been stopped in my tracks by such a change.

Now I'm up on the latest versions of Stencil and Bazel as well.

The Rollup plugin that I injected via `stencil.config.ts` was [pasted in this merge request comment](https://github.com/ionic-team/stencil/pull/2981#issuecomment-889244508)

Here is the same plugin again for convenience:


```ts
  rollupPlugins: {
    // Plugins injected before rollupNodeResolve()
    before: [
      // This plugin is required to overwrite the `preserveSymlinks` rollup
      // config option so that Bazel can resolve files while running Stencil in
      // the Bazel sandbox.
      {
        name: 'overwrite-rollup-options',
        options: (options: RollupInputOptions) => {
          return {
            ...options,
            preserveSymlinks: true,
          };
        },
      },
    ],
  },
```


Again, super interested in sharing how awesome Stencil and Bazel and also sharing the current pain points (which are generally around having to publish intermediate packages in order to use something like the React output target).

From my side, since there is a workable solution, this issue could be closed, but maybe you want to track documenting this somewhere, or take some other action. I'll leave the issue closing to you, the new maintainers 🙂 

Thanks @splitinfinities for jumping into this topic!
